// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addresses.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const clearDefaultAddresses = `-- name: ClearDefaultAddresses :exec
UPDATE addresses
SET is_default = false
WHERE user_id = $1
`

func (q *Queries) ClearDefaultAddresses(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearDefaultAddresses, userID)
	return err
}

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (user_id, recipient_name, line1, line2, city, state, postal_code, country_code, phone_e164, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, recipient_name, line1, line2, city, state, postal_code, country_code, phone_e164, is_default, created_at
`

type CreateAddressParams struct {
	UserID        uuid.UUID      `json:"user_id"`
	RecipientName string         `json:"recipient_name"`
	Line1         string         `json:"line1"`
	Line2         sql.NullString `json:"line2"`
	City          string         `json:"city"`
	State         string         `json:"state"`
	PostalCode    string         `json:"postal_code"`
	CountryCode   string         `json:"country_code"`
	PhoneE164     sql.NullString `json:"phone_e164"`
	IsDefault     bool           `json:"is_default"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, createAddress,
		arg.UserID,
		arg.RecipientName,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.CountryCode,
		arg.PhoneE164,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecipientName,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.CountryCode,
		&i.PhoneE164,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM addresses
WHERE id = $1 AND user_id = $2
`

type DeleteAddressParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) error {
	_, err := q.db.ExecContext(ctx, deleteAddress, arg.ID, arg.UserID)
	return err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, user_id, recipient_name, line1, line2, city, state, postal_code, country_code, phone_e164, is_default, created_at FROM addresses
WHERE id = $1
`

func (q *Queries) GetAddressByID(ctx context.Context, id uuid.UUID) (Address, error) {
	row := q.db.QueryRowContext(ctx, getAddressByID, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecipientName,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.CountryCode,
		&i.PhoneE164,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const listAddressesByUser = `-- name: ListAddressesByUser :many
SELECT id, user_id, recipient_name, line1, line2, city, state, postal_code, country_code, phone_e164, is_default, created_at FROM addresses
WHERE user_id = $1
ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) ListAddressesByUser(ctx context.Context, userID uuid.UUID) ([]Address, error) {
	rows, err := q.db.QueryContext(ctx, listAddressesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RecipientName,
			&i.Line1,
			&i.Line2,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.CountryCode,
			&i.PhoneE164,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultAddress = `-- name: SetDefaultAddress :one
UPDATE addresses
SET is_default = true
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, recipient_name, line1, line2, city, state, postal_code, country_code, phone_e164, is_default, created_at
`

type SetDefaultAddressParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, setDefaultAddress, arg.ID, arg.UserID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecipientName,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.CountryCode,
		&i.PhoneE164,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE addresses
SET recipient_name = $2,
    line1          = $3,
    line2          = $4,
    city           = $5,
    state          = $6,
    postal_code    = $7,
    country_code   = $8,
    phone_e164     = $9
WHERE id = $1
RETURNING id, user_id, recipient_name, line1, line2, city, state, postal_code, country_code, phone_e164, is_default, created_at
`

type UpdateAddressParams struct {
	ID            uuid.UUID      `json:"id"`
	RecipientName string         `json:"recipient_name"`
	Line1         string         `json:"line1"`
	Line2         sql.NullString `json:"line2"`
	City          string         `json:"city"`
	State         string         `json:"state"`
	PostalCode    string         `json:"postal_code"`
	CountryCode   string         `json:"country_code"`
	PhoneE164     sql.NullString `json:"phone_e164"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, updateAddress,
		arg.ID,
		arg.RecipientName,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.CountryCode,
		arg.PhoneE164,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecipientName,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.CountryCode,
		&i.PhoneE164,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}
