// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (order_id, actor_user_id, event_type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, actor_user_id, event_type, payload, created_at
`

type CreateAuditEventParams struct {
	OrderID     uuid.NullUUID         `json:"order_id"`
	ActorUserID uuid.NullUUID         `json:"actor_user_id"`
	EventType   string                `json:"event_type"`
	Payload     pqtype.NullRawMessage `json:"payload"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRowContext(ctx, createAuditEvent,
		arg.OrderID,
		arg.ActorUserID,
		arg.EventType,
		arg.Payload,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ActorUserID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEventsByOrder = `-- name: ListAuditEventsByOrder :many
SELECT id, order_id, actor_user_id, event_type, payload, created_at FROM audit_events
WHERE order_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAuditEventsByOrder(ctx context.Context, orderID uuid.NullUUID) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ActorUserID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
