// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consents.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createConsent = `-- name: CreateConsent :one
INSERT INTO consents (user_id, consent_type, policy_version, granted_at)
VALUES ($1, $2, $3, now())
RETURNING id, user_id, consent_type, policy_version, granted_at, withdrawn_at
`

type CreateConsentParams struct {
	UserID        uuid.UUID `json:"user_id"`
	ConsentType   string    `json:"consent_type"`
	PolicyVersion string    `json:"policy_version"`
}

func (q *Queries) CreateConsent(ctx context.Context, arg CreateConsentParams) (Consent, error) {
	row := q.db.QueryRowContext(ctx, createConsent, arg.UserID, arg.ConsentType, arg.PolicyVersion)
	var i Consent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConsentType,
		&i.PolicyVersion,
		&i.GrantedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const getConsentsByUser = `-- name: GetConsentsByUser :many
SELECT id, user_id, consent_type, policy_version, granted_at, withdrawn_at FROM consents
WHERE user_id = $1
ORDER BY granted_at DESC
`

func (q *Queries) GetConsentsByUser(ctx context.Context, userID uuid.UUID) ([]Consent, error) {
	rows, err := q.db.QueryContext(ctx, getConsentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Consent
	for rows.Next() {
		var i Consent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConsentType,
			&i.PolicyVersion,
			&i.GrantedAt,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const withdrawConsent = `-- name: WithdrawConsent :exec
UPDATE consents
SET withdrawn_at = now()
WHERE user_id = $1 AND consent_type = $2 AND withdrawn_at IS NULL
`

type WithdrawConsentParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ConsentType string    `json:"consent_type"`
}

func (q *Queries) WithdrawConsent(ctx context.Context, arg WithdrawConsentParams) error {
	_, err := q.db.ExecContext(ctx, withdrawConsent, arg.UserID, arg.ConsentType)
	return err
}
