// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact_queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createContactQuery = `-- name: CreateContactQuery :one
INSERT INTO contact_queries (name, email, phone, subject, message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, phone, subject, message, created_at
`

type CreateContactQueryParams struct {
	Name    string         `json:"name"`
	Email   string         `json:"email"`
	Phone   sql.NullString `json:"phone"`
	Subject sql.NullString `json:"subject"`
	Message string         `json:"message"`
}

func (q *Queries) CreateContactQuery(ctx context.Context, arg CreateContactQueryParams) (ContactQuery, error) {
	row := q.db.QueryRowContext(ctx, createContactQuery,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Subject,
		arg.Message,
	)
	var i ContactQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Subject,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listContactQueries = `-- name: ListContactQueries :many
SELECT id, name, email, phone, subject, message, created_at FROM contact_queries
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListContactQueriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListContactQueries(ctx context.Context, arg ListContactQueriesParams) ([]ContactQuery, error) {
	rows, err := q.db.QueryContext(ctx, listContactQueries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactQuery
	for rows.Next() {
		var i ContactQuery
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Subject,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
