// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coupon_users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCouponUser = `-- name: CreateCouponUser :one
INSERT INTO coupon_users (user_id, coupon_id)
VALUES ($1, $2)
RETURNING id, user_id, coupon_id, created_at, updated_at
`

type CreateCouponUserParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CouponID uuid.UUID `json:"coupon_id"`
}

func (q *Queries) CreateCouponUser(ctx context.Context, arg CreateCouponUserParams) (CouponUser, error) {
	row := q.db.QueryRowContext(ctx, createCouponUser, arg.UserID, arg.CouponID)
	var i CouponUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CouponID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCouponUserByUserAndCoupon = `-- name: GetCouponUserByUserAndCoupon :one
SELECT id, user_id, coupon_id, created_at, updated_at FROM coupon_users
WHERE user_id = $1 AND coupon_id = $2
`

type GetCouponUserByUserAndCouponParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CouponID uuid.UUID `json:"coupon_id"`
}

func (q *Queries) GetCouponUserByUserAndCoupon(ctx context.Context, arg GetCouponUserByUserAndCouponParams) (CouponUser, error) {
	row := q.db.QueryRowContext(ctx, getCouponUserByUserAndCoupon, arg.UserID, arg.CouponID)
	var i CouponUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CouponID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCouponUsersByCoupon = `-- name: ListCouponUsersByCoupon :many
SELECT id, user_id, coupon_id, created_at, updated_at FROM coupon_users
WHERE coupon_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCouponUsersByCoupon(ctx context.Context, couponID uuid.UUID) ([]CouponUser, error) {
	rows, err := q.db.QueryContext(ctx, listCouponUsersByCoupon, couponID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CouponUser
	for rows.Next() {
		var i CouponUser
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CouponID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
