// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coupons.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (name, description, code, is_enable, type, percent, flat, coupon_expiry)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, description, code, is_enable, type, percent, flat, coupon_expiry, created_at, updated_at
`

type CreateCouponParams struct {
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Code         string         `json:"code"`
	IsEnable     bool           `json:"is_enable"`
	Type         string         `json:"type"`
	Percent      sql.NullInt32  `json:"percent"`
	Flat         sql.NullInt32  `json:"flat"`
	CouponExpiry sql.NullTime   `json:"coupon_expiry"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, createCoupon,
		arg.Name,
		arg.Description,
		arg.Code,
		arg.IsEnable,
		arg.Type,
		arg.Percent,
		arg.Flat,
		arg.CouponExpiry,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.IsEnable,
		&i.Type,
		&i.Percent,
		&i.Flat,
		&i.CouponExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, name, description, code, is_enable, type, percent, flat, coupon_expiry, created_at, updated_at FROM coupons
WHERE code = $1 AND is_enable = true
`

func (q *Queries) GetCouponByCode(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, getCouponByCode, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.IsEnable,
		&i.Type,
		&i.Percent,
		&i.Flat,
		&i.CouponExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCouponByID = `-- name: GetCouponByID :one
SELECT id, name, description, code, is_enable, type, percent, flat, coupon_expiry, created_at, updated_at FROM coupons
WHERE id = $1
`

func (q *Queries) GetCouponByID(ctx context.Context, id uuid.UUID) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, getCouponByID, id)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.IsEnable,
		&i.Type,
		&i.Percent,
		&i.Flat,
		&i.CouponExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCoupons = `-- name: ListCoupons :many
SELECT id, name, description, code, is_enable, type, percent, flat, coupon_expiry, created_at, updated_at FROM coupons
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCouponsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCoupons(ctx context.Context, arg ListCouponsParams) ([]Coupon, error) {
	rows, err := q.db.QueryContext(ctx, listCoupons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coupon
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Code,
			&i.IsEnable,
			&i.Type,
			&i.Percent,
			&i.Flat,
			&i.CouponExpiry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoupon = `-- name: UpdateCoupon :one
UPDATE coupons
SET name          = $2,
    description   = $3,
    is_enable     = $4,
    coupon_expiry = $5,
    updated_at    = now()
WHERE id = $1
RETURNING id, name, description, code, is_enable, type, percent, flat, coupon_expiry, created_at, updated_at
`

type UpdateCouponParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	IsEnable     bool           `json:"is_enable"`
	CouponExpiry sql.NullTime   `json:"coupon_expiry"`
}

func (q *Queries) UpdateCoupon(ctx context.Context, arg UpdateCouponParams) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, updateCoupon,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsEnable,
		arg.CouponExpiry,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.IsEnable,
		&i.Type,
		&i.Percent,
		&i.Flat,
		&i.CouponExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
