// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory_items (product_id, on_hand, reserved, reorder_threshold)
VALUES ($1, $2, $3, $4)
RETURNING product_id, on_hand, reserved, reorder_threshold, updated_at
`

type CreateInventoryItemParams struct {
	ProductID        uuid.UUID `json:"product_id"`
	OnHand           int32     `json:"on_hand"`
	Reserved         int32     `json:"reserved"`
	ReorderThreshold int32     `json:"reorder_threshold"`
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, createInventoryItem,
		arg.ProductID,
		arg.OnHand,
		arg.Reserved,
		arg.ReorderThreshold,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ProductID,
		&i.OnHand,
		&i.Reserved,
		&i.ReorderThreshold,
		&i.UpdatedAt,
	)
	return i, err
}

const deductStock = `-- name: DeductStock :one
UPDATE inventory_items
SET on_hand    = on_hand - $2,
    reserved   = reserved - $2,
    updated_at = now()
WHERE product_id = $1
RETURNING product_id, on_hand, reserved, reorder_threshold, updated_at
`

type DeductStockParams struct {
	ProductID uuid.UUID `json:"product_id"`
	OnHand    int32     `json:"on_hand"`
}

func (q *Queries) DeductStock(ctx context.Context, arg DeductStockParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, deductStock, arg.ProductID, arg.OnHand)
	var i InventoryItem
	err := row.Scan(
		&i.ProductID,
		&i.OnHand,
		&i.Reserved,
		&i.ReorderThreshold,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryByProduct = `-- name: GetInventoryByProduct :one
SELECT product_id, on_hand, reserved, reorder_threshold, updated_at FROM inventory_items
WHERE product_id = $1
`

func (q *Queries) GetInventoryByProduct(ctx context.Context, productID uuid.UUID) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, getInventoryByProduct, productID)
	var i InventoryItem
	err := row.Scan(
		&i.ProductID,
		&i.OnHand,
		&i.Reserved,
		&i.ReorderThreshold,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryForUpdate = `-- name: GetInventoryForUpdate :one
SELECT product_id, on_hand, reserved, reorder_threshold, updated_at FROM inventory_items
WHERE product_id = $1
FOR UPDATE
`

func (q *Queries) GetInventoryForUpdate(ctx context.Context, productID uuid.UUID) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, getInventoryForUpdate, productID)
	var i InventoryItem
	err := row.Scan(
		&i.ProductID,
		&i.OnHand,
		&i.Reserved,
		&i.ReorderThreshold,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseStock = `-- name: ReleaseStock :one
UPDATE inventory_items
SET reserved   = reserved - $2,
    updated_at = now()
WHERE product_id = $1
RETURNING product_id, on_hand, reserved, reorder_threshold, updated_at
`

type ReleaseStockParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Reserved  int32     `json:"reserved"`
}

func (q *Queries) ReleaseStock(ctx context.Context, arg ReleaseStockParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, releaseStock, arg.ProductID, arg.Reserved)
	var i InventoryItem
	err := row.Scan(
		&i.ProductID,
		&i.OnHand,
		&i.Reserved,
		&i.ReorderThreshold,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveStock = `-- name: ReserveStock :one
UPDATE inventory_items
SET reserved   = reserved + $2,
    updated_at = now()
WHERE product_id = $1
RETURNING product_id, on_hand, reserved, reorder_threshold, updated_at
`

type ReserveStockParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Reserved  int32     `json:"reserved"`
}

func (q *Queries) ReserveStock(ctx context.Context, arg ReserveStockParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, reserveStock, arg.ProductID, arg.Reserved)
	var i InventoryItem
	err := row.Scan(
		&i.ProductID,
		&i.OnHand,
		&i.Reserved,
		&i.ReorderThreshold,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInventory = `-- name: UpdateInventory :one
UPDATE inventory_items
SET on_hand           = $2,
    reorder_threshold = $3,
    updated_at        = now()
WHERE product_id = $1
RETURNING product_id, on_hand, reserved, reorder_threshold, updated_at
`

type UpdateInventoryParams struct {
	ProductID        uuid.UUID `json:"product_id"`
	OnHand           int32     `json:"on_hand"`
	ReorderThreshold int32     `json:"reorder_threshold"`
}

func (q *Queries) UpdateInventory(ctx context.Context, arg UpdateInventoryParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, updateInventory, arg.ProductID, arg.OnHand, arg.ReorderThreshold)
	var i InventoryItem
	err := row.Scan(
		&i.ProductID,
		&i.OnHand,
		&i.Reserved,
		&i.ReorderThreshold,
		&i.UpdatedAt,
	)
	return i, err
}
