// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type OrderStatus string

const (
	OrderStatusPendingPayment OrderStatus = "pending_payment"
	OrderStatusPaid           OrderStatus = "paid"
	OrderStatusPacked         OrderStatus = "packed"
	OrderStatusShipped        OrderStatus = "shipped"
	OrderStatusDelivered      OrderStatus = "delivered"
	OrderStatusCancelled      OrderStatus = "cancelled"
	OrderStatusPaymentFailed  OrderStatus = "payment_failed"
	OrderStatusRefunded       OrderStatus = "refunded"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type UserRole string

const (
	UserRoleAdmin    UserRole = "admin"
	UserRoleCustomer UserRole = "customer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Address struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	RecipientName string         `json:"recipient_name"`
	Line1         string         `json:"line1"`
	Line2         sql.NullString `json:"line2"`
	City          string         `json:"city"`
	State         string         `json:"state"`
	PostalCode    string         `json:"postal_code"`
	CountryCode   string         `json:"country_code"`
	PhoneE164     sql.NullString `json:"phone_e164"`
	IsDefault     bool           `json:"is_default"`
	CreatedAt     time.Time      `json:"created_at"`
}

type AuditEvent struct {
	ID          uuid.UUID             `json:"id"`
	OrderID     uuid.NullUUID         `json:"order_id"`
	ActorUserID uuid.NullUUID         `json:"actor_user_id"`
	EventType   string                `json:"event_type"`
	Payload     pqtype.NullRawMessage `json:"payload"`
	CreatedAt   time.Time             `json:"created_at"`
}

type Cart struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Category struct {
	ID          uuid.UUID      `json:"id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Consent struct {
	ID            uuid.UUID    `json:"id"`
	UserID        uuid.UUID    `json:"user_id"`
	ConsentType   string       `json:"consent_type"`
	PolicyVersion string       `json:"policy_version"`
	GrantedAt     time.Time    `json:"granted_at"`
	WithdrawnAt   sql.NullTime `json:"withdrawn_at"`
}

type ContactQuery struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Subject   sql.NullString `json:"subject"`
	Message   string         `json:"message"`
	CreatedAt time.Time      `json:"created_at"`
}

type Coupon struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Code         string         `json:"code"`
	IsEnable     bool           `json:"is_enable"`
	Type         string         `json:"type"`
	Percent      sql.NullInt32  `json:"percent"`
	Flat         sql.NullInt32  `json:"flat"`
	CouponExpiry sql.NullTime   `json:"coupon_expiry"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type CouponUser struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	CouponID  uuid.UUID `json:"coupon_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type InventoryItem struct {
	ProductID        uuid.UUID `json:"product_id"`
	OnHand           int32     `json:"on_hand"`
	Reserved         int32     `json:"reserved"`
	ReorderThreshold int32     `json:"reorder_threshold"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Order struct {
	ID           uuid.UUID    `json:"id"`
	UserID       uuid.UUID    `json:"user_id"`
	OrderNumber  string       `json:"order_number"`
	Status       OrderStatus  `json:"status"`
	SubtotalInr  string       `json:"subtotal_inr"`
	ShippingInr  string       `json:"shipping_inr"`
	TaxInr       string       `json:"tax_inr"`
	TotalInr     string       `json:"total_inr"`
	CurrencyCode string       `json:"currency_code"`
	PlacedAt     sql.NullTime `json:"placed_at"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type OrderAddress struct {
	ID            uuid.UUID      `json:"id"`
	OrderID       uuid.UUID      `json:"order_id"`
	RecipientName string         `json:"recipient_name"`
	Line1         string         `json:"line1"`
	Line2         sql.NullString `json:"line2"`
	City          string         `json:"city"`
	State         string         `json:"state"`
	PostalCode    string         `json:"postal_code"`
	CountryCode   string         `json:"country_code"`
	PhoneE164     sql.NullString `json:"phone_e164"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type OrderItem struct {
	ID           uuid.UUID     `json:"id"`
	OrderID      uuid.UUID     `json:"order_id"`
	ProductID    uuid.NullUUID `json:"product_id"`
	ProductTitle string        `json:"product_title"`
	ProductSku   string        `json:"product_sku"`
	Quantity     int32         `json:"quantity"`
	UnitPriceInr string        `json:"unit_price_inr"`
	LineTotalInr string        `json:"line_total_inr"`
}

type Payment struct {
	ID                uuid.UUID             `json:"id"`
	OrderID           uuid.UUID             `json:"order_id"`
	Provider          string                `json:"provider"`
	ProviderOrderID   string                `json:"provider_order_id"`
	ProviderPaymentID sql.NullString        `json:"provider_payment_id"`
	Status            string                `json:"status"`
	AmountInr         string                `json:"amount_inr"`
	GatewayPayload    pqtype.NullRawMessage `json:"gateway_payload"`
	CreatedAt         time.Time             `json:"created_at"`
	UpdatedAt         time.Time             `json:"updated_at"`
}

type Product struct {
	ID              uuid.UUID      `json:"id"`
	CategoryID      uuid.UUID      `json:"category_id"`
	Sku             string         `json:"sku"`
	Slug            string         `json:"slug"`
	Title           string         `json:"title"`
	AuthorName      string         `json:"author_name"`
	Isbn13          sql.NullString `json:"isbn13"`
	Description     sql.NullString `json:"description"`
	PriceInr        string         `json:"price_inr"`
	DiscountPercent sql.NullInt32  `json:"discount_percent"`
	ImageUrl        sql.NullString `json:"image_url"`
	CurrencyCode    string         `json:"currency_code"`
	LanguageCode    sql.NullString `json:"language_code"`
	PageCount       sql.NullInt32  `json:"page_count"`
	PublicationDate sql.NullTime   `json:"publication_date"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	SearchVector    interface{}    `json:"search_vector"`
}

type ProductAttribute struct {
	ID           uuid.UUID `json:"id"`
	Code         string    `json:"code"`
	Name         string    `json:"name"`
	IsFilterable bool      `json:"is_filterable"`
	SortOrder    int32     `json:"sort_order"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type ProductAttributeAssignment struct {
	ProductID        uuid.UUID `json:"product_id"`
	AttributeValueID uuid.UUID `json:"attribute_value_id"`
	CreatedAt        time.Time `json:"created_at"`
}

type ProductAttributeValue struct {
	ID          uuid.UUID `json:"id"`
	AttributeID uuid.UUID `json:"attribute_id"`
	Value       string    `json:"value"`
	Slug        string    `json:"slug"`
	SortOrder   int32     `json:"sort_order"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ProductImage struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
	ImageUrl  string    `json:"image_url"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RefreshToken struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	TokenFamilyID string         `json:"token_family_id"`
	TokenHash     string         `json:"token_hash"`
	UserAgent     sql.NullString `json:"user_agent"`
	IpAddress     pqtype.Inet    `json:"ip_address"`
	ExpiresAt     time.Time      `json:"expires_at"`
	RevokedAt     sql.NullTime   `json:"revoked_at"`
	CreatedAt     time.Time      `json:"created_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	FullName     string         `json:"full_name"`
	PhoneE164    sql.NullString `json:"phone_e164"`
	Role         UserRole       `json:"role"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
}
