// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, product_title, product_sku, quantity, unit_price_inr, line_total_inr)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, order_id, product_id, product_title, product_sku, quantity, unit_price_inr, line_total_inr
`

type CreateOrderItemParams struct {
	OrderID      uuid.UUID     `json:"order_id"`
	ProductID    uuid.NullUUID `json:"product_id"`
	ProductTitle string        `json:"product_title"`
	ProductSku   string        `json:"product_sku"`
	Quantity     int32         `json:"quantity"`
	UnitPriceInr string        `json:"unit_price_inr"`
	LineTotalInr string        `json:"line_total_inr"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.ProductTitle,
		arg.ProductSku,
		arg.Quantity,
		arg.UnitPriceInr,
		arg.LineTotalInr,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductTitle,
		&i.ProductSku,
		&i.Quantity,
		&i.UnitPriceInr,
		&i.LineTotalInr,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, product_title, product_sku, quantity, unit_price_inr, line_total_inr FROM order_items
WHERE order_id = $1
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductTitle,
			&i.ProductSku,
			&i.Quantity,
			&i.UnitPriceInr,
			&i.LineTotalInr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
