// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_address.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOrderAddress = `-- name: CreateOrderAddress :one
INSERT INTO order_address (order_id, recipient_name, line1, line2, city, state, postal_code, country_code, phone_e164)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, order_id, recipient_name, line1, line2, city, state, postal_code, country_code, phone_e164, created_at, updated_at
`

type CreateOrderAddressParams struct {
	OrderID       uuid.UUID      `json:"order_id"`
	RecipientName string         `json:"recipient_name"`
	Line1         string         `json:"line1"`
	Line2         sql.NullString `json:"line2"`
	City          string         `json:"city"`
	State         string         `json:"state"`
	PostalCode    string         `json:"postal_code"`
	CountryCode   string         `json:"country_code"`
	PhoneE164     sql.NullString `json:"phone_e164"`
}

func (q *Queries) CreateOrderAddress(ctx context.Context, arg CreateOrderAddressParams) (OrderAddress, error) {
	row := q.db.QueryRowContext(ctx, createOrderAddress,
		arg.OrderID,
		arg.RecipientName,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.CountryCode,
		arg.PhoneE164,
	)
	var i OrderAddress
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.RecipientName,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.CountryCode,
		&i.PhoneE164,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderAddress = `-- name: GetOrderAddress :one
SELECT id, order_id, recipient_name, line1, line2, city, state, postal_code, country_code, phone_e164, created_at, updated_at FROM order_address
WHERE order_id = $1
`

func (q *Queries) GetOrderAddress(ctx context.Context, orderID uuid.UUID) (OrderAddress, error) {
	row := q.db.QueryRowContext(ctx, getOrderAddress, orderID)
	var i OrderAddress
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.RecipientName,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.CountryCode,
		&i.PhoneE164,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
