// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, order_number, status, subtotal_inr, shipping_inr, tax_inr, total_inr, currency_code, placed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
RETURNING id, user_id, order_number, status, subtotal_inr, shipping_inr, tax_inr, total_inr, currency_code, placed_at, created_at, updated_at
`

type CreateOrderParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	OrderNumber  string      `json:"order_number"`
	Status       OrderStatus `json:"status"`
	SubtotalInr  string      `json:"subtotal_inr"`
	ShippingInr  string      `json:"shipping_inr"`
	TaxInr       string      `json:"tax_inr"`
	TotalInr     string      `json:"total_inr"`
	CurrencyCode string      `json:"currency_code"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.UserID,
		arg.OrderNumber,
		arg.Status,
		arg.SubtotalInr,
		arg.ShippingInr,
		arg.TaxInr,
		arg.TotalInr,
		arg.CurrencyCode,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderNumber,
		&i.Status,
		&i.SubtotalInr,
		&i.ShippingInr,
		&i.TaxInr,
		&i.TotalInr,
		&i.CurrencyCode,
		&i.PlacedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, order_number, status, subtotal_inr, shipping_inr, tax_inr, total_inr, currency_code, placed_at, created_at, updated_at FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderNumber,
		&i.Status,
		&i.SubtotalInr,
		&i.ShippingInr,
		&i.TaxInr,
		&i.TotalInr,
		&i.CurrencyCode,
		&i.PlacedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT id, user_id, order_number, status, subtotal_inr, shipping_inr, tax_inr, total_inr, currency_code, placed_at, created_at, updated_at FROM orders
WHERE order_number = $1
`

func (q *Queries) GetOrderByNumber(ctx context.Context, orderNumber string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByNumber, orderNumber)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderNumber,
		&i.Status,
		&i.SubtotalInr,
		&i.ShippingInr,
		&i.TaxInr,
		&i.TotalInr,
		&i.CurrencyCode,
		&i.PlacedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, order_number, status, subtotal_inr, shipping_inr, tax_inr, total_inr, currency_code, placed_at, created_at, updated_at FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderNumber,
			&i.Status,
			&i.SubtotalInr,
			&i.ShippingInr,
			&i.TaxInr,
			&i.TotalInr,
			&i.CurrencyCode,
			&i.PlacedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status     = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, order_number, status, subtotal_inr, shipping_inr, tax_inr, total_inr, currency_code, placed_at, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status OrderStatus `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderNumber,
		&i.Status,
		&i.SubtotalInr,
		&i.ShippingInr,
		&i.TaxInr,
		&i.TotalInr,
		&i.CurrencyCode,
		&i.PlacedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
