// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, provider, provider_order_id, status, amount_inr, gateway_payload)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, provider, provider_order_id, provider_payment_id, status, amount_inr, gateway_payload, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID         uuid.UUID             `json:"order_id"`
	Provider        string                `json:"provider"`
	ProviderOrderID string                `json:"provider_order_id"`
	Status          string                `json:"status"`
	AmountInr       string                `json:"amount_inr"`
	GatewayPayload  pqtype.NullRawMessage `json:"gateway_payload"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.OrderID,
		arg.Provider,
		arg.ProviderOrderID,
		arg.Status,
		arg.AmountInr,
		arg.GatewayPayload,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ProviderPaymentID,
		&i.Status,
		&i.AmountInr,
		&i.GatewayPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByProviderOrderID = `-- name: GetPaymentByProviderOrderID :one
SELECT id, order_id, provider, provider_order_id, provider_payment_id, status, amount_inr, gateway_payload, created_at, updated_at FROM payments
WHERE provider_order_id = $1
`

func (q *Queries) GetPaymentByProviderOrderID(ctx context.Context, providerOrderID string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByProviderOrderID, providerOrderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ProviderPaymentID,
		&i.Status,
		&i.AmountInr,
		&i.GatewayPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentsByOrder = `-- name: GetPaymentsByOrder :many
SELECT id, order_id, provider, provider_order_id, provider_payment_id, status, amount_inr, gateway_payload, created_at, updated_at FROM payments
WHERE order_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPaymentsByOrder(ctx context.Context, orderID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getPaymentsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Provider,
			&i.ProviderOrderID,
			&i.ProviderPaymentID,
			&i.Status,
			&i.AmountInr,
			&i.GatewayPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status              = $2,
    provider_payment_id = $3,
    gateway_payload     = $4,
    updated_at          = now()
WHERE id = $1
RETURNING id, order_id, provider, provider_order_id, provider_payment_id, status, amount_inr, gateway_payload, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID                uuid.UUID             `json:"id"`
	Status            string                `json:"status"`
	ProviderPaymentID sql.NullString        `json:"provider_payment_id"`
	GatewayPayload    pqtype.NullRawMessage `json:"gateway_payload"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentStatus,
		arg.ID,
		arg.Status,
		arg.ProviderPaymentID,
		arg.GatewayPayload,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ProviderPaymentID,
		&i.Status,
		&i.AmountInr,
		&i.GatewayPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
