// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    category_id, sku, slug, title, author_name, isbn13, description,
    price_inr, discount_percent, image_url, currency_code, language_code,
    page_count, publication_date, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, $15
)
RETURNING id, category_id, sku, slug, title, author_name, isbn13, description,
          price_inr, discount_percent, image_url, currency_code, language_code,
          page_count, publication_date, is_active, created_at, updated_at
`

type CreateProductParams struct {
	CategoryID      uuid.UUID      `json:"category_id"`
	Sku             string         `json:"sku"`
	Slug            string         `json:"slug"`
	Title           string         `json:"title"`
	AuthorName      string         `json:"author_name"`
	Isbn13          sql.NullString `json:"isbn13"`
	Description     sql.NullString `json:"description"`
	PriceInr        string         `json:"price_inr"`
	DiscountPercent sql.NullInt32  `json:"discount_percent"`
	ImageUrl        sql.NullString `json:"image_url"`
	CurrencyCode    string         `json:"currency_code"`
	LanguageCode    sql.NullString `json:"language_code"`
	PageCount       sql.NullInt32  `json:"page_count"`
	PublicationDate sql.NullTime   `json:"publication_date"`
	IsActive        bool           `json:"is_active"`
}

type CreateProductRow struct {
	ID              uuid.UUID      `json:"id"`
	CategoryID      uuid.UUID      `json:"category_id"`
	Sku             string         `json:"sku"`
	Slug            string         `json:"slug"`
	Title           string         `json:"title"`
	AuthorName      string         `json:"author_name"`
	Isbn13          sql.NullString `json:"isbn13"`
	Description     sql.NullString `json:"description"`
	PriceInr        string         `json:"price_inr"`
	DiscountPercent sql.NullInt32  `json:"discount_percent"`
	ImageUrl        sql.NullString `json:"image_url"`
	CurrencyCode    string         `json:"currency_code"`
	LanguageCode    sql.NullString `json:"language_code"`
	PageCount       sql.NullInt32  `json:"page_count"`
	PublicationDate sql.NullTime   `json:"publication_date"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.CategoryID,
		arg.Sku,
		arg.Slug,
		arg.Title,
		arg.AuthorName,
		arg.Isbn13,
		arg.Description,
		arg.PriceInr,
		arg.DiscountPercent,
		arg.ImageUrl,
		arg.CurrencyCode,
		arg.LanguageCode,
		arg.PageCount,
		arg.PublicationDate,
		arg.IsActive,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Sku,
		&i.Slug,
		&i.Title,
		&i.AuthorName,
		&i.Isbn13,
		&i.Description,
		&i.PriceInr,
		&i.DiscountPercent,
		&i.ImageUrl,
		&i.CurrencyCode,
		&i.LanguageCode,
		&i.PageCount,
		&i.PublicationDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, category_id, sku, slug, title, author_name, isbn13, description,
       price_inr, discount_percent, image_url, currency_code, language_code,
       page_count, publication_date, is_active, created_at, updated_at
FROM products
WHERE id = $1
`

type GetProductByIDRow struct {
	ID              uuid.UUID      `json:"id"`
	CategoryID      uuid.UUID      `json:"category_id"`
	Sku             string         `json:"sku"`
	Slug            string         `json:"slug"`
	Title           string         `json:"title"`
	AuthorName      string         `json:"author_name"`
	Isbn13          sql.NullString `json:"isbn13"`
	Description     sql.NullString `json:"description"`
	PriceInr        string         `json:"price_inr"`
	DiscountPercent sql.NullInt32  `json:"discount_percent"`
	ImageUrl        sql.NullString `json:"image_url"`
	CurrencyCode    string         `json:"currency_code"`
	LanguageCode    sql.NullString `json:"language_code"`
	PageCount       sql.NullInt32  `json:"page_count"`
	PublicationDate sql.NullTime   `json:"publication_date"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Sku,
		&i.Slug,
		&i.Title,
		&i.AuthorName,
		&i.Isbn13,
		&i.Description,
		&i.PriceInr,
		&i.DiscountPercent,
		&i.ImageUrl,
		&i.CurrencyCode,
		&i.LanguageCode,
		&i.PageCount,
		&i.PublicationDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, category_id, sku, slug, title, author_name, isbn13, description,
       price_inr, discount_percent, image_url, currency_code, language_code,
       page_count, publication_date, is_active, created_at, updated_at
FROM products
WHERE slug = $1 AND is_active = true
`

type GetProductBySlugRow struct {
	ID              uuid.UUID      `json:"id"`
	CategoryID      uuid.UUID      `json:"category_id"`
	Sku             string         `json:"sku"`
	Slug            string         `json:"slug"`
	Title           string         `json:"title"`
	AuthorName      string         `json:"author_name"`
	Isbn13          sql.NullString `json:"isbn13"`
	Description     sql.NullString `json:"description"`
	PriceInr        string         `json:"price_inr"`
	DiscountPercent sql.NullInt32  `json:"discount_percent"`
	ImageUrl        sql.NullString `json:"image_url"`
	CurrencyCode    string         `json:"currency_code"`
	LanguageCode    sql.NullString `json:"language_code"`
	PageCount       sql.NullInt32  `json:"page_count"`
	PublicationDate sql.NullTime   `json:"publication_date"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Sku,
		&i.Slug,
		&i.Title,
		&i.AuthorName,
		&i.Isbn13,
		&i.Description,
		&i.PriceInr,
		&i.DiscountPercent,
		&i.ImageUrl,
		&i.CurrencyCode,
		&i.LanguageCode,
		&i.PageCount,
		&i.PublicationDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, category_id, sku, slug, title, author_name, isbn13, description,
       price_inr, discount_percent, image_url, currency_code, language_code,
       page_count, publication_date, is_active, created_at, updated_at
FROM products
WHERE is_active = true
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductsRow struct {
	ID              uuid.UUID      `json:"id"`
	CategoryID      uuid.UUID      `json:"category_id"`
	Sku             string         `json:"sku"`
	Slug            string         `json:"slug"`
	Title           string         `json:"title"`
	AuthorName      string         `json:"author_name"`
	Isbn13          sql.NullString `json:"isbn13"`
	Description     sql.NullString `json:"description"`
	PriceInr        string         `json:"price_inr"`
	DiscountPercent sql.NullInt32  `json:"discount_percent"`
	ImageUrl        sql.NullString `json:"image_url"`
	CurrencyCode    string         `json:"currency_code"`
	LanguageCode    sql.NullString `json:"language_code"`
	PageCount       sql.NullInt32  `json:"page_count"`
	PublicationDate sql.NullTime   `json:"publication_date"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Sku,
			&i.Slug,
			&i.Title,
			&i.AuthorName,
			&i.Isbn13,
			&i.Description,
			&i.PriceInr,
			&i.DiscountPercent,
			&i.ImageUrl,
			&i.CurrencyCode,
			&i.LanguageCode,
			&i.PageCount,
			&i.PublicationDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT id, category_id, sku, slug, title, author_name, isbn13, description,
       price_inr, discount_percent, image_url, currency_code, language_code,
       page_count, publication_date, is_active, created_at, updated_at
FROM products
WHERE category_id = $1 AND is_active = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsByCategoryParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type ListProductsByCategoryRow struct {
	ID              uuid.UUID      `json:"id"`
	CategoryID      uuid.UUID      `json:"category_id"`
	Sku             string         `json:"sku"`
	Slug            string         `json:"slug"`
	Title           string         `json:"title"`
	AuthorName      string         `json:"author_name"`
	Isbn13          sql.NullString `json:"isbn13"`
	Description     sql.NullString `json:"description"`
	PriceInr        string         `json:"price_inr"`
	DiscountPercent sql.NullInt32  `json:"discount_percent"`
	ImageUrl        sql.NullString `json:"image_url"`
	CurrencyCode    string         `json:"currency_code"`
	LanguageCode    sql.NullString `json:"language_code"`
	PageCount       sql.NullInt32  `json:"page_count"`
	PublicationDate sql.NullTime   `json:"publication_date"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]ListProductsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsByCategoryRow
	for rows.Next() {
		var i ListProductsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Sku,
			&i.Slug,
			&i.Title,
			&i.AuthorName,
			&i.Isbn13,
			&i.Description,
			&i.PriceInr,
			&i.DiscountPercent,
			&i.ImageUrl,
			&i.CurrencyCode,
			&i.LanguageCode,
			&i.PageCount,
			&i.PublicationDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, category_id, sku, slug, title, author_name, isbn13, description,
       price_inr, discount_percent, image_url, currency_code, language_code,
       page_count, publication_date, is_active, created_at, updated_at
FROM products
WHERE is_active = true
  AND search_vector @@ plainto_tsquery('english', $1)
ORDER BY ts_rank(search_vector, plainto_tsquery('english', $1)) DESC
LIMIT $2 OFFSET $3
`

type SearchProductsParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

type SearchProductsRow struct {
	ID              uuid.UUID      `json:"id"`
	CategoryID      uuid.UUID      `json:"category_id"`
	Sku             string         `json:"sku"`
	Slug            string         `json:"slug"`
	Title           string         `json:"title"`
	AuthorName      string         `json:"author_name"`
	Isbn13          sql.NullString `json:"isbn13"`
	Description     sql.NullString `json:"description"`
	PriceInr        string         `json:"price_inr"`
	DiscountPercent sql.NullInt32  `json:"discount_percent"`
	ImageUrl        sql.NullString `json:"image_url"`
	CurrencyCode    string         `json:"currency_code"`
	LanguageCode    sql.NullString `json:"language_code"`
	PageCount       sql.NullInt32  `json:"page_count"`
	PublicationDate sql.NullTime   `json:"publication_date"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchProducts, arg.PlaintoTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProductsRow
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Sku,
			&i.Slug,
			&i.Title,
			&i.AuthorName,
			&i.Isbn13,
			&i.Description,
			&i.PriceInr,
			&i.DiscountPercent,
			&i.ImageUrl,
			&i.CurrencyCode,
			&i.LanguageCode,
			&i.PageCount,
			&i.PublicationDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET category_id      = $2,
    title            = $3,
    author_name      = $4,
    description      = $5,
    price_inr        = $6,
    discount_percent = $7,
    image_url        = $8,
    is_active        = $9,
    updated_at       = now()
WHERE id = $1
RETURNING id, category_id, sku, slug, title, author_name, isbn13, description,
          price_inr, discount_percent, image_url, currency_code, language_code,
          page_count, publication_date, is_active, created_at, updated_at
`

type UpdateProductParams struct {
	ID              uuid.UUID      `json:"id"`
	CategoryID      uuid.UUID      `json:"category_id"`
	Title           string         `json:"title"`
	AuthorName      string         `json:"author_name"`
	Description     sql.NullString `json:"description"`
	PriceInr        string         `json:"price_inr"`
	DiscountPercent sql.NullInt32  `json:"discount_percent"`
	ImageUrl        sql.NullString `json:"image_url"`
	IsActive        bool           `json:"is_active"`
}

type UpdateProductRow struct {
	ID              uuid.UUID      `json:"id"`
	CategoryID      uuid.UUID      `json:"category_id"`
	Sku             string         `json:"sku"`
	Slug            string         `json:"slug"`
	Title           string         `json:"title"`
	AuthorName      string         `json:"author_name"`
	Isbn13          sql.NullString `json:"isbn13"`
	Description     sql.NullString `json:"description"`
	PriceInr        string         `json:"price_inr"`
	DiscountPercent sql.NullInt32  `json:"discount_percent"`
	ImageUrl        sql.NullString `json:"image_url"`
	CurrencyCode    string         `json:"currency_code"`
	LanguageCode    sql.NullString `json:"language_code"`
	PageCount       sql.NullInt32  `json:"page_count"`
	PublicationDate sql.NullTime   `json:"publication_date"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Title,
		arg.AuthorName,
		arg.Description,
		arg.PriceInr,
		arg.DiscountPercent,
		arg.ImageUrl,
		arg.IsActive,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Sku,
		&i.Slug,
		&i.Title,
		&i.AuthorName,
		&i.Isbn13,
		&i.Description,
		&i.PriceInr,
		&i.DiscountPercent,
		&i.ImageUrl,
		&i.CurrencyCode,
		&i.LanguageCode,
		&i.PageCount,
		&i.PublicationDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
