// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_attributes.sql

package sqlc

import (
	"context"
)

const createAttribute = `-- name: CreateAttribute :one
INSERT INTO product_attributes (code, name, is_filterable, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, is_filterable, sort_order, created_at, updated_at
`

type CreateAttributeParams struct {
	Code         string `json:"code"`
	Name         string `json:"name"`
	IsFilterable bool   `json:"is_filterable"`
	SortOrder    int32  `json:"sort_order"`
}

func (q *Queries) CreateAttribute(ctx context.Context, arg CreateAttributeParams) (ProductAttribute, error) {
	row := q.db.QueryRowContext(ctx, createAttribute,
		arg.Code,
		arg.Name,
		arg.IsFilterable,
		arg.SortOrder,
	)
	var i ProductAttribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsFilterable,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttributeByCode = `-- name: GetAttributeByCode :one
SELECT id, code, name, is_filterable, sort_order, created_at, updated_at FROM product_attributes
WHERE code = $1
`

func (q *Queries) GetAttributeByCode(ctx context.Context, code string) (ProductAttribute, error) {
	row := q.db.QueryRowContext(ctx, getAttributeByCode, code)
	var i ProductAttribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsFilterable,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAttributes = `-- name: ListAttributes :many
SELECT id, code, name, is_filterable, sort_order, created_at, updated_at FROM product_attributes
ORDER BY sort_order, name
`

func (q *Queries) ListAttributes(ctx context.Context) ([]ProductAttribute, error) {
	rows, err := q.db.QueryContext(ctx, listAttributes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductAttribute
	for rows.Next() {
		var i ProductAttribute
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IsFilterable,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilterableAttributes = `-- name: ListFilterableAttributes :many
SELECT id, code, name, is_filterable, sort_order, created_at, updated_at FROM product_attributes
WHERE is_filterable = true
ORDER BY sort_order, name
`

func (q *Queries) ListFilterableAttributes(ctx context.Context) ([]ProductAttribute, error) {
	rows, err := q.db.QueryContext(ctx, listFilterableAttributes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductAttribute
	for rows.Next() {
		var i ProductAttribute
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IsFilterable,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
