// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_attribute_assignments.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignAttributeToProduct = `-- name: AssignAttributeToProduct :one
INSERT INTO product_attribute_assignments (product_id, attribute_value_id)
VALUES ($1, $2)
RETURNING product_id, attribute_value_id, created_at
`

type AssignAttributeToProductParams struct {
	ProductID        uuid.UUID `json:"product_id"`
	AttributeValueID uuid.UUID `json:"attribute_value_id"`
}

func (q *Queries) AssignAttributeToProduct(ctx context.Context, arg AssignAttributeToProductParams) (ProductAttributeAssignment, error) {
	row := q.db.QueryRowContext(ctx, assignAttributeToProduct, arg.ProductID, arg.AttributeValueID)
	var i ProductAttributeAssignment
	err := row.Scan(&i.ProductID, &i.AttributeValueID, &i.CreatedAt)
	return i, err
}

const getAttributesByProduct = `-- name: GetAttributesByProduct :many
SELECT pav.id, pav.attribute_id, pav.value, pav.slug, pav.sort_order, pav.created_at, pav.updated_at, pa.code AS attribute_code, pa.name AS attribute_name
FROM product_attribute_assignments paa
JOIN product_attribute_values pav ON pav.id = paa.attribute_value_id
JOIN product_attributes pa ON pa.id = pav.attribute_id
WHERE paa.product_id = $1
ORDER BY pa.sort_order, pav.sort_order
`

type GetAttributesByProductRow struct {
	ID            uuid.UUID `json:"id"`
	AttributeID   uuid.UUID `json:"attribute_id"`
	Value         string    `json:"value"`
	Slug          string    `json:"slug"`
	SortOrder     int32     `json:"sort_order"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	AttributeCode string    `json:"attribute_code"`
	AttributeName string    `json:"attribute_name"`
}

func (q *Queries) GetAttributesByProduct(ctx context.Context, productID uuid.UUID) ([]GetAttributesByProductRow, error) {
	rows, err := q.db.QueryContext(ctx, getAttributesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttributesByProductRow
	for rows.Next() {
		var i GetAttributesByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.AttributeID,
			&i.Value,
			&i.Slug,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AttributeCode,
			&i.AttributeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAttributeFromProduct = `-- name: RemoveAttributeFromProduct :exec
DELETE FROM product_attribute_assignments
WHERE product_id = $1 AND attribute_value_id = $2
`

type RemoveAttributeFromProductParams struct {
	ProductID        uuid.UUID `json:"product_id"`
	AttributeValueID uuid.UUID `json:"attribute_value_id"`
}

func (q *Queries) RemoveAttributeFromProduct(ctx context.Context, arg RemoveAttributeFromProductParams) error {
	_, err := q.db.ExecContext(ctx, removeAttributeFromProduct, arg.ProductID, arg.AttributeValueID)
	return err
}
