// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_attribute_values.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAttributeValue = `-- name: CreateAttributeValue :one
INSERT INTO product_attribute_values (attribute_id, value, slug, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, attribute_id, value, slug, sort_order, created_at, updated_at
`

type CreateAttributeValueParams struct {
	AttributeID uuid.UUID `json:"attribute_id"`
	Value       string    `json:"value"`
	Slug        string    `json:"slug"`
	SortOrder   int32     `json:"sort_order"`
}

func (q *Queries) CreateAttributeValue(ctx context.Context, arg CreateAttributeValueParams) (ProductAttributeValue, error) {
	row := q.db.QueryRowContext(ctx, createAttributeValue,
		arg.AttributeID,
		arg.Value,
		arg.Slug,
		arg.SortOrder,
	)
	var i ProductAttributeValue
	err := row.Scan(
		&i.ID,
		&i.AttributeID,
		&i.Value,
		&i.Slug,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttributeValueByID = `-- name: GetAttributeValueByID :one
SELECT id, attribute_id, value, slug, sort_order, created_at, updated_at FROM product_attribute_values
WHERE id = $1
`

func (q *Queries) GetAttributeValueByID(ctx context.Context, id uuid.UUID) (ProductAttributeValue, error) {
	row := q.db.QueryRowContext(ctx, getAttributeValueByID, id)
	var i ProductAttributeValue
	err := row.Scan(
		&i.ID,
		&i.AttributeID,
		&i.Value,
		&i.Slug,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listValuesByAttribute = `-- name: ListValuesByAttribute :many
SELECT id, attribute_id, value, slug, sort_order, created_at, updated_at FROM product_attribute_values
WHERE attribute_id = $1
ORDER BY sort_order, value
`

func (q *Queries) ListValuesByAttribute(ctx context.Context, attributeID uuid.UUID) ([]ProductAttributeValue, error) {
	rows, err := q.db.QueryContext(ctx, listValuesByAttribute, attributeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductAttributeValue
	for rows.Next() {
		var i ProductAttributeValue
		if err := rows.Scan(
			&i.ID,
			&i.AttributeID,
			&i.Value,
			&i.Slug,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
