// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignAttributeToProduct(ctx context.Context, arg AssignAttributeToProductParams) (ProductAttributeAssignment, error)
	ClearCart(ctx context.Context, userID uuid.UUID) error
	ClearDefaultAddresses(ctx context.Context, userID uuid.UUID) error
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateAttribute(ctx context.Context, arg CreateAttributeParams) (ProductAttribute, error)
	CreateAttributeValue(ctx context.Context, arg CreateAttributeValueParams) (ProductAttributeValue, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateConsent(ctx context.Context, arg CreateConsentParams) (Consent, error)
	CreateContactQuery(ctx context.Context, arg CreateContactQueryParams) (ContactQuery, error)
	CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error)
	CreateCouponUser(ctx context.Context, arg CreateCouponUserParams) (CouponUser, error)
	CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderAddress(ctx context.Context, arg CreateOrderAddressParams) (OrderAddress, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeductStock(ctx context.Context, arg DeductStockParams) (InventoryItem, error)
	DeleteAddress(ctx context.Context, arg DeleteAddressParams) error
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteProductImage(ctx context.Context, id uuid.UUID) error
	GetAddressByID(ctx context.Context, id uuid.UUID) (Address, error)
	GetAttributeByCode(ctx context.Context, code string) (ProductAttribute, error)
	GetAttributeValueByID(ctx context.Context, id uuid.UUID) (ProductAttributeValue, error)
	GetAttributesByProduct(ctx context.Context, productID uuid.UUID) ([]GetAttributesByProductRow, error)
	GetCartByUser(ctx context.Context, userID uuid.UUID) ([]Cart, error)
	GetCartItem(ctx context.Context, arg GetCartItemParams) (Cart, error)
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetConsentsByUser(ctx context.Context, userID uuid.UUID) ([]Consent, error)
	GetCouponByCode(ctx context.Context, code string) (Coupon, error)
	GetCouponByID(ctx context.Context, id uuid.UUID) (Coupon, error)
	GetCouponUserByUserAndCoupon(ctx context.Context, arg GetCouponUserByUserAndCouponParams) (CouponUser, error)
	GetInventoryByProduct(ctx context.Context, productID uuid.UUID) (InventoryItem, error)
	GetInventoryForUpdate(ctx context.Context, productID uuid.UUID) (InventoryItem, error)
	GetOrderAddress(ctx context.Context, orderID uuid.UUID) (OrderAddress, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderByNumber(ctx context.Context, orderNumber string) (Order, error)
	GetPaymentByProviderOrderID(ctx context.Context, providerOrderID string) (Payment, error)
	GetPaymentsByOrder(ctx context.Context, orderID uuid.UUID) ([]Payment, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListAddressesByUser(ctx context.Context, userID uuid.UUID) ([]Address, error)
	ListAttributes(ctx context.Context) ([]ProductAttribute, error)
	ListAuditEventsByOrder(ctx context.Context, orderID uuid.NullUUID) ([]AuditEvent, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListContactQueries(ctx context.Context, arg ListContactQueriesParams) ([]ContactQuery, error)
	ListCouponUsersByCoupon(ctx context.Context, couponID uuid.UUID) ([]CouponUser, error)
	ListCoupons(ctx context.Context, arg ListCouponsParams) ([]Coupon, error)
	ListFilterableAttributes(ctx context.Context) ([]ProductAttribute, error)
	ListImagesByProduct(ctx context.Context, productID uuid.UUID) ([]ProductImage, error)
	ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]ListProductsByCategoryRow, error)
	ListValuesByAttribute(ctx context.Context, attributeID uuid.UUID) ([]ProductAttributeValue, error)
	ReleaseStock(ctx context.Context, arg ReleaseStockParams) (InventoryItem, error)
	RemoveAttributeFromProduct(ctx context.Context, arg RemoveAttributeFromProductParams) error
	ReserveStock(ctx context.Context, arg ReserveStockParams) (InventoryItem, error)
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	RevokeTokenFamily(ctx context.Context, tokenFamilyID string) error
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error)
	SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) (Address, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCoupon(ctx context.Context, arg UpdateCouponParams) (Coupon, error)
	UpdateInventory(ctx context.Context, arg UpdateInventoryParams) (InventoryItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (Cart, error)
	WithdrawConsent(ctx context.Context, arg WithdrawConsentParams) error
}

var _ Querier = (*Queries)(nil)
